spring:
  jpa:
    hibernate:
      ddl-auto: validate

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/tbotdb
    username: tbotdb
    password: tbotdb